version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/topdust    
permissions:
  - object: /var/www/topdust
    pattern: "**"    
    owner: ubuntu
    group: ubuntu
    mode: 644
    type:
      - file
  - object: /var/www/topdust
    pattern: "**"    
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - directory
hooks:    
    AfterInstall:
    - location: scripts/movetos3.sh
      timeout: 180
      runas: ubuntu
