version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/topdust
  - source: /index1.html
    destination: /var/www/topdust
  - source: /test/test.html
    destination: /var/www/topdust/test
  - source: /new
    destination: /var/www/topdust/new
permissions:
  - object: /var/www/topdust
    pattern: "**"
    except: [index.html]
    owner: ubuntu
    group: ubuntu
    mode: 644
    type:
      - file
